### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by jhalx** [icpd/subscribe2clash#12]
我本来自己下载了源码 想改出想要的功能 
奈何太菜 
调试一番 没有解决 

需求就是 当我提交的数据是属于clash的常规正常配置 （有proxies proxygroups providers时）最好是保留原有分组 当然 如果你有更好的分析和判断方式 改就改了吧 （这个不是重点），然后修改其规则 为你配置的规则 或者保留其规则 添加一个参数来指定他 或者 添加一个不同的路由 ，然后再重新下载下来。
简而言之 ，尽可能的保留节点原本信息，可选性的修改规则。

**Comment by jhalx** [comment]
> 我目前的处理方式就是 发现他是clash规则 就原封不动的 输出 改了好几个小时 整不会了 ，看不懂啊 裂开

**Comment by jhalx** [comment]
对了 还有那个规则 acl之类的规则 建议 获取文件的修改时间 配置为 半天更新一次 或者更久 因为不是运行在服务器上 而是本地 所以 经常会频繁开启 每次都需要下载一次规则 比较浪费时间  当规则下载失败 也可以使用以前的副本 也存有旧数据直接使用 而不会导致转换失败

**Comment by whoisix** [comment]
> 对了 还有那个规则 acl之类的规则 建议 获取文件的修改时间 配置为 半天更新一次 或者更久 因为不是运行在服务器上 而是本地 所以 经常会频繁开启 每次都需要下载一次规则 比较浪费时间  当规则下载失败 也可以使用以前的副本 也存有旧数据直接使用 而不会导致转换失败

可以指定更新时间，单位是小时

**Comment by whoisix** [comment]
> 对了 还有那个规则 acl之类的规则 建议 获取文件的修改时间 配置为 半天更新一次 或者更久 因为不是运行在服务器上 而是本地 所以 经常会频繁开启 每次都需要下载一次规则 比较浪费时间  当规则下载失败 也可以使用以前的副本 也存有旧数据直接使用 而不会导致转换失败

本地已经有了，启动的时候就不拉规则吗？这个可以考虑一下

**Comment by icpd** [comment]
> clash的常规正常配置 （有proxies proxygroups providers时）最好是保留原有分组 然后修改其规则 为你配置的规则
这还真不好做，因为无法确定下载下来的分组应该对应什么规则

> 或者保留其规则 添加一个参数来指定他 或者 添加一个不同的路由 ，然后再重新下载下来。
添加参数指定什么？
添加路由下载特定的配置？
