### ISSUE TITLE
提示 key "cipher" missing

### ISSUE THREAD

**Issue by bigfuji** [icpd/subscribe2clash#22]
使用freefq节点
使用windows版本
转换后的文件放入clash for windows中
提示 key "cipher" missing

**Comment by icpd** [comment]
可以提供更多的配置相关信息吗，或者你的临时订阅链接

**Comment by icpd** [comment]
是用的ssr吗？

**Comment by icpd** [comment]
如果你有编译环境可否尝试一下 [omitempty_tag](https://github.com/icpd/subscribe2clash/tree/omitempty_tag) 分支是否已解决了你的问题
