### ISSUE TITLE
[feature] 希望能够直接从命令行转换订阅链接，不需要打开web服务

### ISSUE THREAD

**Issue by gsy44355** [icpd/subscribe2clash#26]
如题，查看readme发现并不能够直接在命令行通过输入参数的方式加载订阅链接，直接输出文件

**Comment by icpd** [comment]
但在命令行输入长长的原订阅链接，看起来似乎不是很友好

**Comment by gsy44355** [comment]
> 但在命令行输入长长的原订阅链接，看起来似乎不是很友好

我理解有我这种需求的往往是一些习惯命令行的人- -这样可以全程使用脚本，现在我的使用逻辑是先打开服务，然后wget，再pkill，相当于绕了一圈。

**Comment by icpd** [comment]
可以考虑实现

**Comment by icpd** [comment]
今年有些忙，可能需要等一段时间才能实现

另外想知道一下`nodeonly`是指生成文件的意思吗？
