### ISSUE TITLE
link 参数中有多个参数的话会丢失参数

### ISSUE THREAD

**Issue by snakem982** [icpd/subscribe2clash#45]
1、比如入参这样
link=https://wanshanziwo.eu.org/clash/proxies?c=CN,HK,TW&type=trojan
代码会丢失参数type=trojan
向原地址发起请求

2、参数中有逗号的话入参多个订阅地址也会报错，建议多个订阅地址用 | 分割

**Comment by icpd** [comment]
可以先把订阅链接urlencode处理一下

**Comment by snakem982** [comment]
这样也可以，现在代码里有解码操作？

**Comment by icpd** [comment]
好像没有哈哈，空了加上

**Comment by snakem982** [comment]
perfect  文档也记得更新下
